feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: ./data/ntu/NTU60_CV.npz
  split: train
  window_size: 64
  p_interval: [0.5, 1]
  

test_feeder_args:
  data_path: ./data/ntu/NTU60_CV.npz
  split: test
  window_size: 64
  p_interval: [0.95]